// GENERATED by scripts/roadmap.mjs from `roadkeep export --json` — do not edit by hand.
// Regenerated on every build (S2). Edit the roadmap through roadkeep, not this file.
import type { RoadmapData } from "./roadmap-types";

export const roadmap: RoadmapData = {
  "prefix": "DD",
  "blocks": [
    {
      "label": "A",
      "title": "A — The Windows engine (Docker without Docker Desktop)",
      "open": 3,
      "shipped": 14,
      "retired": 0
    },
    {
      "label": "B",
      "title": "B — The daemon client (talk to the engine)",
      "open": 0,
      "shipped": 2,
      "retired": 0
    },
    {
      "label": "C",
      "title": "C — The window (claude-tray's elements)",
      "open": 8,
      "shipped": 12,
      "retired": 0
    },
    {
      "label": "D",
      "title": "D — Container operations (what a user came to do)",
      "open": 0,
      "shipped": 3,
      "retired": 0
    },
    {
      "label": "E",
      "title": "E — Images, volumes and networks",
      "open": 0,
      "shipped": 2,
      "retired": 0
    },
    {
      "label": "F",
      "title": "F — Installer and distribution (free, Apache 2.0)",
      "open": 0,
      "shipped": 7,
      "retired": 0
    },
    {
      "label": "G",
      "title": "G — The agent surface (an agent operates this, and pays in tokens)",
      "open": 3,
      "shipped": 15,
      "retired": 0
    },
    {
      "label": "H",
      "title": "H — The public surface (the site a reader and an agent both read)",
      "open": 1,
      "shipped": 16,
      "retired": 0
    }
  ],
  "totals": {
    "open": 15,
    "shipped": 71,
    "retired": 0
  },
  "open": [
    {
      "id": "DD75",
      "status": "📋",
      "block": "A",
      "symptom": "A bind mount spelled the Windows way is sent to a Linux daemon that resolves only its own paths",
      "why": "Docker Desktop rewrites a drive path into a host mount inside its VM and nothing here does, so a compose file with a relative volume arrives as a source the daemon never chose.",
      "deps": []
    },
    {
      "id": "DD76",
      "status": "💭",
      "block": "A",
      "symptom": "docker inside a user WSL2 distribution reaches nothing, the toggle Docker Desktop calls WSL integration",
      "why": "The socket lives in the owned distribution and its only way out is a pipe a Linux client cannot dial, so a developer whose shell is Ubuntu has no engine at all.",
      "deps": []
    },
    {
      "id": "DD86",
      "status": "📋",
      "block": "A",
      "symptom": "The old name survives as adoption code and an agent skill, for a product that has no installed base to adopt",
      "why": "Three shipped tasks bought compatibility with installs that were never made, and the cost is a second name in the paths, the labels, the rival probe and the installer.",
      "deps": []
    },
    {
      "id": "DD67",
      "status": "💭",
      "block": "C",
      "symptom": "No popup this product draws has ever been photographed, and the one path that could is not reachable",
      "why": "DD61 made the screen copy refuse the shell, which is right, and left the script with nothing it can find: a menu exists only while open, and nothing opens one.",
      "deps": []
    },
    {
      "id": "DD69",
      "status": "📋",
      "block": "C",
      "symptom": "The window carries none of the ocean the mark swims in, and its lowest strip is margin and then the frame",
      "why": "The site closes its hero into water and opens its footer out of it, so a window with no trace of that reads as a different product from the one the mark introduces.",
      "deps": []
    },
    {
      "id": "DD70",
      "status": "📋",
      "block": "C",
      "symptom": "A list that changed under a refresh and an engine that is still starting both arrive with no transition",
      "why": "Motion is what tells a reader that a thing changed rather than that they misread it, and this window redraws rows and holds a pending engine with none at all.",
      "deps": [
        "DD69"
      ]
    },
    {
      "id": "DD80",
      "status": "📋",
      "block": "C",
      "symptom": "Launching the executable shows nothing, and the shortcuts the installer writes carry no window verb",
      "why": "CommandLine reads a bare argv as tray-only, so Explorer, the Start menu and the desktop icon all land in silence, and a user with no feedback clicks again.",
      "deps": []
    },
    {
      "id": "DD81",
      "status": "📋",
      "block": "C",
      "symptom": "A second launch starts a second tray rather than raising the first, so two icons and two event streams run",
      "why": "Nothing holds a mutex, so each extra click is another process polling the daemon; raising the first window and exiting is the answer, not an error a click cannot show.",
      "deps": [
        "DD80"
      ]
    },
    {
      "id": "DD82",
      "status": "📋",
      "block": "C",
      "symptom": "Visible is set before the icon and tooltip exist, so Windows persists an empty tooltip for the tray entry",
      "why": "The add carries no icon flag and no text, and the overflow flyout is exactly where that empty tooltip is read, so the place the icon lands names nothing.",
      "deps": []
    },
    {
      "id": "DD83",
      "status": "📋",
      "block": "C",
      "symptom": "Nothing in the window names the build, the engine version behind it, or the API version the client speaks",
      "why": "A version is the first thing a bug report asks for and the only way to tell a stale install from a fresh one, and the console verb answers where a window user never looks.",
      "deps": [
        "DD69"
      ]
    },
    {
      "id": "DD85",
      "status": "📋",
      "block": "C",
      "symptom": "The tray icon is three abstract rings, so the one surface always on screen carries none of the product mark",
      "why": "The mark is the only thing a user recognises at a glance, and a ring says nothing about which product is running while three of them sit in one overflow.",
      "deps": []
    },
    {
      "id": "DD77",
      "status": "📋",
      "block": "G",
      "symptom": "Nothing says a machine still carries objects labelled the way the build before the rename wrote them",
      "why": "So the dual read has no end: the legacy key cannot be dropped without evidence nobody can gather, and every read pays for a generation that may already be gone.",
      "deps": []
    },
    {
      "id": "DD78",
      "status": "📋",
      "block": "G",
      "symptom": "The shaped token figure is banded because two of its inputs are read from the machine and not a fixture",
      "why": "A 15% band is wide enough to hide a regression a build could ship, and the request count recorded beside it is exact for want of the same seam.",
      "deps": []
    },
    {
      "id": "DD79",
      "status": "📋",
      "block": "G",
      "symptom": "SessionLabel.For reads as the one place a label is stamped and nothing in the product stamps through it",
      "why": "ComposeUp writes the key straight into YAML, so the helper is reached only by a test and the next change to a label has two places to find rather than one.",
      "deps": []
    },
    {
      "id": "DD84",
      "status": "🛠",
      "block": "H",
      "symptom": "The published site serves no robots.txt and no sitemap.xml, and both answer 404 where the old folder had them",
      "why": "Nothing tells a crawler which routes exist, so discovery rests on whatever links inward, and the sitemap the old folder published is gone rather than replaced.",
      "deps": []
    }
  ],
  "ledger": [
    {
      "id": "DD1",
      "status": "✅",
      "block": "A",
      "symptom": "A Windows user cannot tell why Docker will not run here: WSL2 missing, virtualization off, or a rival engine",
      "why": "`freewilly --preflight` reports the Windows build, virtualization, the WSL2 kernel and any rival engine one row each with the action that fixes it, and exits 1 while a blocker is not green.",
      "deps": []
    },
    {
      "id": "DD2",
      "status": "✅",
      "block": "A",
      "symptom": "There is no unattended way to put a container engine on Windows without installing Docker Desktop",
      "why": "`freewilly --provision` puts upstream Moby 29.7.2 in an owned WSL2 distro and docker.exe where an installer can add it to PATH.",
      "deps": []
    },
    {
      "id": "DD17",
      "status": "✅",
      "block": "A",
      "symptom": "No clean Windows is reachable from here, so a red preflight row and a real install have never been executed",
      "why": "`vm.ps1` runs the product preflight inside a Windows 11 guest through vmrun and reads back what it said.",
      "deps": []
    },
    {
      "id": "DD3",
      "status": "✅",
      "block": "A",
      "symptom": "Nothing starts or stops the engine, and a UI that reports running before the socket answers is lying",
      "why": "`freewilly --run` starts the distro and daemon, serves \\\\.\\pipe\\docker_engine, and reports Running only once the engine answers.",
      "deps": []
    },
    {
      "id": "DD16",
      "status": "✅",
      "block": "A",
      "symptom": "The preflight reports no rival engine on a machine where Docker Desktop is installed per-user and `docker` is on PATH",
      "why": "The row now asks what owns the docker command, resolving it off PATH the way a shell does and reading the registered WSL distributions, and it names every signal it found.",
      "deps": []
    },
    {
      "id": "DD18",
      "status": "✅",
      "block": "A",
      "symptom": "On a Windows 11 that never had WSL, the preflight spends 15 seconds saying it could not read the WSL2 row",
      "why": "The row asks `wsl --status` first, so a bare machine is named in milliseconds with the remedy that applies, and `--version` is only reached once something says WSL is there.",
      "deps": []
    },
    {
      "id": "DD19",
      "status": "✅",
      "block": "A",
      "symptom": "Inside a VM the preflight calls virtualization enabled and clears an install that WSL2 then refuses to start",
      "why": "The row reads whether this machine is itself a guest, and abstains inside one instead of reading HypervisorPresent as proof it can host a hypervisor.",
      "deps": []
    },
    {
      "id": "DD20",
      "status": "✅",
      "block": "A",
      "symptom": "A leftover docker context sends the CLI to another pipe, so docker reports no daemon while this engine is answering",
      "why": "A preflight row reads the active context and names both endpoints, so a CLI pointing elsewhere is visible, and it changes no setting of the user's.",
      "deps": []
    },
    {
      "id": "DD52",
      "status": "✅",
      "block": "A",
      "symptom": "The rival row prints its evidence as one 254-character line, and wrapping it on spaces splits a path",
      "why": "The rival row names the products and puts each path, pipe and distribution on its own line, whole - so the evidence can be copied into a shell or grepped, and the JSON report carries it as a list.",
      "deps": []
    },
    {
      "id": "DD55",
      "status": "✅",
      "block": "A",
      "symptom": "The engine owns a WSL distribution and an app root both named dockerdesk, and a rename orphans them",
      "why": "An install made before the rename is adopted where it stands: both names resolve from what is on disk and registered, and nothing moves - distro is the BasePath WSL holds.",
      "deps": []
    },
    {
      "id": "DD56",
      "status": "✅",
      "block": "A",
      "symptom": "The rival probe carries a rule that exists only because dockerdesk contains docker, and freewilly does not",
      "why": "Both names this project has owned are skipped by name before the rival table is consulted, so an adopted install is never told to uninstall the engine it is running.",
      "deps": []
    },
    {
      "id": "DD68",
      "status": "✅",
      "block": "A",
      "symptom": "The console-width guard asserts on every rendered line, including the evidence lines DD52 must not wrap",
      "why": "The remedy's wrap width is the renderer's only length rule and is named as a constant, and a second test states out loud that an evidence line may exceed it.",
      "deps": []
    },
    {
      "id": "DD73",
      "status": "✅",
      "block": "A",
      "symptom": "docker compose is not a command on a clean install, and the do compose verb shells into exactly that",
      "why": "Compose is a fourth pinned artefact placed under this install's own cli-plugins, and the bundled call sets DOCKER_CONFIG so docker compose is a subcommand.",
      "deps": []
    },
    {
      "id": "DD74",
      "status": "✅",
      "block": "A",
      "symptom": "No buildx is placed, so a Dockerfile with a cache mount or a heredoc cannot build on a clean install",
      "why": "Buildx is a fifth pinned artefact placed beside Compose, so docker build is BuildKit and a cache mount stops failing on the mount option.",
      "deps": []
    },
    {
      "id": "DD4",
      "status": "✅",
      "block": "B",
      "symptom": "Nothing in this project can ask the engine anything: no client for the Docker API over the Windows named pipe",
      "why": "DockerApi speaks the Engine API over the named pipe with no NuGet dependency: ping, version, containers, and a stream for endpoints that never end.",
      "deps": []
    },
    {
      "id": "DD5",
      "status": "✅",
      "block": "B",
      "symptom": "A container started in a terminal never appears in the window, and the list is only as fresh as the last refresh",
      "why": "EngineEvents reads /events as the daemon writes it and re-opens the stream after every break, so nothing here polls.",
      "deps": []
    },
    {
      "id": "DD6",
      "status": "✅",
      "block": "C",
      "symptom": "Answering is Docker up? costs opening a window, and starting the engine costs a command line",
      "why": "A tray icon carries the engine state as a shape, and its menu starts the engine in a process that outlives the tray or stops it.",
      "deps": []
    },
    {
      "id": "DD7",
      "status": "✅",
      "block": "C",
      "symptom": "There is no window: a user cannot see which containers exist, their state, or the ports they publish",
      "why": "A WPF window lists containers with their ports as links, refreshed by the event stream, and says something designed when it is empty.",
      "deps": []
    },
    {
      "id": "DD21",
      "status": "✅",
      "block": "C",
      "symptom": "The tray icon was not in the visible notification area while the tray was running, so the glance costs a click",
      "why": "The icon registers and Windows files it into the overflow, so the install says where it went and how to keep it in sight, and nothing here promotes itself.",
      "deps": []
    },
    {
      "id": "DD22",
      "status": "✅",
      "block": "C",
      "symptom": "Verifying a window copies the screen, so a capture twice photographed private content that was in front of it",
      "why": "A --capture-window verb renders the window off-screen so nothing else can be in the frame, and the screen copy kept for popups refuses when anything overlaps it.",
      "deps": []
    },
    {
      "id": "DD34",
      "status": "✅",
      "block": "C",
      "symptom": "The two windows redeclare their chrome and one red is spelled four times, so a meaning has four definitions",
      "why": "The danger red, the engine's three colours and the font stack live in one Palette of bytes, and markup reaches them with x:Static as claude-tray's Brand does.",
      "deps": []
    },
    {
      "id": "DD35",
      "status": "✅",
      "block": "C",
      "symptom": "Three lists, the engine, the logs and the shell share one window class, so a fourth list grows the same two files",
      "why": "The shell keeps the engine line, the terms and a nav strip; each list is a page built on first visit and kept alive, so a fourth adds a file rather than growing two.",
      "deps": []
    },
    {
      "id": "DD66",
      "status": "✅",
      "block": "C",
      "symptom": "Every container row threw while being measured, so the list has drawn nothing since the pages were split",
      "why": "The two styles a row template is BasedOn moved into the page that uses them, where a StaticResource is legal, and a check refuses a DynamicResource on BasedOn.",
      "deps": []
    },
    {
      "id": "DD38",
      "status": "✅",
      "block": "C",
      "symptom": "No window can be drawn without a running daemon holding the containers the picture is meant to show",
      "why": "The window takes a seam rather than the client, and a SampleMachine stands in at it, so --fixture draws every page from a machine that is the same everywhere.",
      "deps": []
    },
    {
      "id": "DD36",
      "status": "✅",
      "block": "C",
      "symptom": "A row says its state in plain text and carries six always-visible captions, so a list of forty reads as a form",
      "why": "State is a tinted chip that tells a clean exit from a kill and carries its own evidence, and the six captions per row are Logs, one verb and an overflow that is always drawn.",
      "deps": []
    },
    {
      "id": "DD37",
      "status": "✅",
      "block": "C",
      "symptom": "No heading sorts and no list filters, so finding one container among forty is done with the scrollbar",
      "why": "Every heading is a button that sorts and carries a glyph, and one box per list narrows over the rows in hand; both are held by the page so a refresh cannot drop them.",
      "deps": []
    },
    {
      "id": "DD39",
      "status": "✅",
      "block": "C",
      "symptom": "The window opens at one fixed size on the primary screen every time and forgets which list was being read",
      "why": "The window opens where it was left, at the size it was left, on the tab that was being read - and a rectangle that no longer lands on a monitor is refused rather than opened off-screen.",
      "deps": []
    },
    {
      "id": "DD61",
      "status": "✅",
      "block": "C",
      "symptom": "A screen copy of the window carries a blurred image of what is behind it, because the Fluent backdrop transmits it",
      "why": "Capture-Window.ps1 asks DWM for the window's system backdrop and refuses to copy one that has it, with no flag to waive it - so the leak is a refusal rather than a printed warning.",
      "deps": []
    },
    {
      "id": "DD8",
      "status": "✅",
      "block": "D",
      "symptom": "The list is read-only: a container cannot be started, stopped, restarted or removed from it",
      "why": "Start, stop, restart and remove on every row: the click lands in a pending state, the event stream is what ends it, and a refusal shows the daemon's own sentence where the button is.",
      "deps": []
    },
    {
      "id": "DD9",
      "status": "✅",
      "block": "D",
      "symptom": "A container that exits immediately shows a state and nothing about the cause, so the user leaves for a terminal",
      "why": "A window per container: frame headers stripped, stderr told from stdout, follow on by default, copy-all to the clipboard, and a buffer capped at 5,000 lines that drops from the front.",
      "deps": []
    },
    {
      "id": "DD10",
      "status": "✅",
      "block": "D",
      "symptom": "There is no way into a running container: no shell, so anything the log does not say is unreachable",
      "why": "The terminal the user already has, running docker exec: the image is asked which shell it has first, so one with neither says so on the row instead of opening a window that closes.",
      "deps": []
    },
    {
      "id": "DD11",
      "status": "✅",
      "block": "E",
      "symptom": "Tens of gigabytes of layers accumulate and nothing says which images are dangling or still in use",
      "why": "Images sorted by size, each row saying whether a container holds it or it is dangling, with per-image removal and a dangling-only prune that names the space before the click and after it.",
      "deps": []
    },
    {
      "id": "DD12",
      "status": "✅",
      "block": "E",
      "symptom": "Volumes are invisible: a user cannot see which exist, what they cost on disk, or which containers mount them",
      "why": "Volumes with their sizes and what mounts them, the compose project read off the name, and a deletion that names all of it first because a volume is the one thing here that does not come back.",
      "deps": []
    },
    {
      "id": "DD13",
      "status": "✅",
      "block": "F",
      "symptom": "Nothing states the terms: a visitor cannot tell this is free at any headcount, and no NOTICE covers the bundled engine",
      "why": "Apache-2.0 stated in the README's first paragraph, in LICENSE and in the window's About, with a NOTICE generated from the install manifest so a new download cannot ship unattributed.",
      "deps": []
    },
    {
      "id": "DD14",
      "status": "✅",
      "block": "F",
      "symptom": "There is nothing to hand a user: no executable, no installer, and no uninstall that respects their data",
      "why": "One FreeWilly.exe with every verb behind an argument, an Inno Setup installer that is per-user with no administrator prompt, and an uninstall that asks before deleting the distribution.",
      "deps": []
    },
    {
      "id": "DD15",
      "status": "✅",
      "block": "F",
      "symptom": "Every release is built on one developer's machine, so the first download finds what that machine hid",
      "why": "Two Windows workflows: a check that builds, tests and starts the published .exe on every push, and a tag that drafts a release carrying SHA-256 sums for a person to publish.",
      "deps": []
    },
    {
      "id": "DD32",
      "status": "✅",
      "block": "F",
      "symptom": "An agent meeting this machine has no way to know the surface exists, so it reaches for docker",
      "why": "A skill naming the verbs, an allowlist line and a generated brief ship with the install, which proposes all three and writes none of them into your configuration.",
      "deps": []
    },
    {
      "id": "DD53",
      "status": "✅",
      "block": "F",
      "symptom": "The test guest cannot be returned to a clean snapshot, so the machine a check was measured on is gone once it drifts",
      "why": "vm.ps1 gained a revert action that names the snapshot and what reverting discards, and refuses without -Yes rather than prompting - so a state a row was measured on is reachable again.",
      "deps": []
    },
    {
      "id": "DD54",
      "status": "✅",
      "block": "F",
      "symptom": "Every project, namespace and assembly in the tree spells DockerDesk, so a rename starts at the solution file",
      "why": "The build spells FreeWilly throughout - projects, namespaces, assembly, icon and the harness - while the app root and the WSL distribution stay behind for DD55 to migrate.",
      "deps": []
    },
    {
      "id": "DD57",
      "status": "✅",
      "block": "F",
      "symptom": "The installer identifies the product by an AppId with the old name inside it, so a rename installs a second one",
      "why": "An old install is upgraded in place: the AppId never changes, the labels around it do, and the Run value the old name owned is deleted rather than left starting a missing exe.",
      "deps": []
    },
    {
      "id": "DD23",
      "status": "✅",
      "block": "G",
      "symptom": "Nothing measures what a Docker task costs an agent, so a cheaper surface is an unfalsifiable claim",
      "why": "A benchmark measures the canonical task at 11711 estimated tokens over six calls, and agent-budget.json is the ceiling it reads, so a response that grew fails a build.",
      "deps": []
    },
    {
      "id": "DD24",
      "status": "✅",
      "block": "G",
      "symptom": "Reading a container and deleting a volume are one allowlist decision, so every read costs an approval",
      "why": "read and do are separate argv namespaces so one allowlist line grants every read, and a test drives each read verb and requires every request it made to be a GET.",
      "deps": []
    },
    {
      "id": "DD25",
      "status": "✅",
      "block": "G",
      "symptom": "Learning what this machine is running costs five commands, and it repeats in full every session",
      "why": "One read context answers the whole machine at 102 estimated tokens against 5718 for the three list reads it replaces, and an OOM row closes the canonical question in the first call.",
      "deps": []
    },
    {
      "id": "DD26",
      "status": "✅",
      "block": "G",
      "symptom": "Why a container is not answering is a join across five commands, and inspect is read for four fields",
      "why": "One read doctor joins the five commands and returns a verdict and a remedy per row over the preflight's own model, including the port fact only Windows can answer.",
      "deps": []
    },
    {
      "id": "DD27",
      "status": "✅",
      "block": "G",
      "symptom": "A container log is read unbounded, so a restart loop is paid for eight times in identical traces",
      "why": "read logs takes a cursor, a level, a dedup that turned 634 estimated tokens into 95, a ceiling it never cuts in silence, and an --out that turns the read into a Grep.",
      "deps": []
    },
    {
      "id": "DD28",
      "status": "✅",
      "block": "G",
      "symptom": "Port is already allocated does not say what holds the port, and the answer is not in Docker at all",
      "why": "A refusal carries the Windows fact that explains it: read ports names the pid holding a port, and cannot connect became three causes with three remedies.",
      "deps": []
    },
    {
      "id": "DD29",
      "status": "✅",
      "block": "G",
      "symptom": "What an agent created is indistinguishable from what the user created, so cleanup is prune or nothing",
      "why": "A confirm token computed over the printed list scopes cleanup to one session's label, so a stale plan refuses instead of deleting what arrived in between.",
      "deps": []
    },
    {
      "id": "DD30",
      "status": "✅",
      "block": "G",
      "symptom": "Nothing proves a service is reachable: a running container with a bound port can answer nothing",
      "why": "A connect from Windows, an optional GET and the health check's own output turn running into answering, and --wait makes the same call the readiness primitive.",
      "deps": []
    },
    {
      "id": "DD31",
      "status": "✅",
      "block": "G",
      "symptom": "Every session re-derives the whole machine, because nothing states what moved since the last one",
      "why": "read changes --since is a delta over the daemon's own bounded history, collapsed per object, and it refuses rather than skipping when the cursor reaches past it.",
      "deps": []
    },
    {
      "id": "DD33",
      "status": "✅",
      "block": "G",
      "symptom": "A client with no shell cannot reach this surface at all, the CLI being the only head there is",
      "why": "The CLI-first inversion is recorded as a decision with a price: a spec that survives shipping, a cap of six tools in the budget file, and a test that no head arrives uncapped.",
      "deps": []
    },
    {
      "id": "DD64",
      "status": "✅",
      "block": "G",
      "symptom": "The test that gates every cost claim can go red for a reason that is not cost",
      "why": "The fake speaks HTTP/1.1, so the close .NET's retry was racing is gone (design §DD64 superseded: it said the fake could not tell a counted body from an EOF-delimited one, and the response says which).",
      "deps": []
    },
    {
      "id": "DD58",
      "status": "✅",
      "block": "G",
      "symptom": "The agent surface is invoked as dockerdesk and quoted that way in allowlist patterns matched literally",
      "why": "The invocation is freewilly everywhere it is quoted, and a guard derives the allowlist pattern from the executable's own name so the two cannot drift into matching nothing.",
      "deps": []
    },
    {
      "id": "DD63",
      "status": "✅",
      "block": "G",
      "symptom": "No verb on this surface creates anything, so the session stamp has nothing to stamp",
      "why": "do compose up is the first verb that creates: the services come from the CLI, a generated override outside the project stamps each one, and the answer names the undo.",
      "deps": []
    },
    {
      "id": "DD65",
      "status": "✅",
      "block": "G",
      "symptom": "The budget file still says the agent surface does not exist, so the ratio it was built to prove is unrecorded",
      "why": "The same task through read context, doctor, logs and verify is 4 calls and 774 tokens against the baseline's 6 and 11711, recorded as task-for-task rather than payload-for-payload.",
      "deps": []
    },
    {
      "id": "DD72",
      "status": "✅",
      "block": "G",
      "symptom": "The session label key is the last name in the rename set that is state on a machine rather than spelling in a build",
      "why": "The key written is freewilly.session and both spellings are read, so a machine mid-migration keeps every session a previous build labelled.",
      "deps": []
    },
    {
      "id": "DD40",
      "status": "✅",
      "block": "H",
      "symptom": "The site is one hand-written page, dark-only, with every claim typed into the markup that displays it",
      "why": "The landing page renders from a Vite React Tailwind workspace: copy in one content module the sections iterate, and the theme follows the OS.",
      "deps": []
    },
    {
      "id": "DD41",
      "status": "✅",
      "block": "H",
      "symptom": "A static host needs a file per route, and nothing checks that a route has a page or a page a title",
      "why": "Each route prerenders to its own file with a replace-or-throw head, and the route map and metadata table assert against each other in both directions at import time.",
      "deps": []
    },
    {
      "id": "DD42",
      "status": "✅",
      "block": "H",
      "symptom": "A Claude-first product answers an agent only in hydrated markup, in the first thing anybody reads",
      "why": "Every route emits a Markdown twin converted from the same render, a manifest lists the routes and their twin sizes, and llms.txt moves into the build with the twin convention.",
      "deps": []
    },
    {
      "id": "DD43",
      "status": "✅",
      "block": "H",
      "symptom": "The status rows are typed into the page, and five of them are already wrong about what has shipped",
      "why": "The status page and the landing summary are generated from roadkeep export --json on every build, so a shipped task moves its own row and no progress figure is typed.",
      "deps": []
    },
    {
      "id": "DD44",
      "status": "✅",
      "block": "H",
      "symptom": "The hero asserts what the tool is, so what it costs an agent per call is nowhere on the page",
      "why": "The hero autoplays the five-call agent session with its per-call token targets, and the transcript scrolls its own list rather than the window.",
      "deps": []
    },
    {
      "id": "DD45",
      "status": "✅",
      "block": "H",
      "symptom": "Nothing on the site says who the operator is, so the positioning is still a GUI with no licence fee",
      "why": "A section per design law in the order an agent meets them, and the two-actor split, replace the GUI-with-no-licence-fee positioning the pre-DD23 page shipped under.",
      "deps": []
    },
    {
      "id": "DD46",
      "status": "✅",
      "block": "H",
      "symptom": "Nobody configuring an agent can find the read and do split, or the one allowlist line that pays for it",
      "why": "A page for the agent's operator: the read/do split, the one allowlist line Bash(freewilly read:*), the DD32 plugin, and the refusals, marked as the designed Block-G surface.",
      "deps": []
    },
    {
      "id": "DD47",
      "status": "✅",
      "block": "H",
      "symptom": "A visitor weighing this against Docker Desktop, Rancher, Podman or a plain WSL2 daemon infers it from prose",
      "why": "A comparison matrix grouped by the law each row comes from, with a column per rival for what it genuinely wins, and a machine-readable table twin.",
      "deps": []
    },
    {
      "id": "DD48",
      "status": "✅",
      "block": "H",
      "symptom": "Everything is one scroll, so a pillar gets a paragraph and there is no page to link at",
      "why": "Five depth pages from one record each, whose route, title and description are read off the same record, so a pillar cannot ship half-declared or untitled.",
      "deps": []
    },
    {
      "id": "DD49",
      "status": "✅",
      "block": "H",
      "symptom": "The og image points at an svg, so every share of this link renders a card with no image at all",
      "why": "A 1200x630 og.png rasterised from public/og.svg on every build, with the mark and the tagline, and og:image points at it on every route.",
      "deps": []
    },
    {
      "id": "DD50",
      "status": "✅",
      "block": "H",
      "symptom": "The site is whatever was last committed to docs, so a broken page is public with no gate between",
      "why": "A workflow_dispatch-only Pages job whose single gate is npm run build (typecheck, the prerender route and head checks), publishing site/dist to the same URL.",
      "deps": []
    },
    {
      "id": "DD51",
      "status": "✅",
      "block": "H",
      "symptom": "A claim on the site that has gone false is invisible until somebody reads the page against the product",
      "why": "node --test asserts the site's own claims: the generated roadmap figures, the route pair and heads, the twin per route with the CTA dropped, the 1200x630 card, and no scrollIntoView.",
      "deps": []
    },
    {
      "id": "DD62",
      "status": "✅",
      "block": "H",
      "symptom": "The page for the agent's operator names only the interruption, so the surface reads as a saving in keystrokes",
      "why": "Eight rows pair what plain docker costs an agent with the verb that replaces it, and every cost, ceiling and shipped badge is generated from agent-budget.json and the verb registry.",
      "deps": []
    },
    {
      "id": "DD60",
      "status": "✅",
      "block": "H",
      "symptom": "Fifteen lines of governed prose name DockerDesk, and the guard denies the edit that would change them",
      "why": "The non-goal, five ledger entries and the skill directory moved through the verb that owns each; what still reads dockerdesk in the prose files is quoting a surface DD59 and DD71 have yet to change.",
      "deps": []
    },
    {
      "id": "DD71",
      "status": "✅",
      "block": "H",
      "symptom": "README and the site still name the product and the distribution as they were before the rename",
      "why": "README, the site copy, llms.txt and the DD23 spec filename name FreeWilly, and the distribution is freewilly with no second name anywhere.",
      "deps": []
    },
    {
      "id": "DD59",
      "status": "✅",
      "block": "H",
      "symptom": "The site is served from a base path containing the old name, so every published route moves at once",
      "why": "The base path, the canonical URL and the repository URL are freewilly everywhere, written once in vite.config.ts, and the site build is green again.",
      "deps": []
    }
  ],
  "next": "DD84"
};
