// GENERATED by scripts/roadmap.mjs from `roadkeep export --json` — do not edit by hand.
// Regenerated on every build (S2). Edit the roadmap through roadkeep, not this file.
import type { RoadmapData } from "./roadmap-types";

export const roadmap: RoadmapData = {
  "prefix": "DD",
  "blocks": [
    {
      "label": "A",
      "title": "A — The Windows engine (Docker without Docker Desktop)",
      "open": 3,
      "shipped": 8,
      "retired": 0
    },
    {
      "label": "B",
      "title": "B — The daemon client (talk to the engine)",
      "open": 0,
      "shipped": 2,
      "retired": 0
    },
    {
      "label": "C",
      "title": "C — The window (claude-tray's elements)",
      "open": 7,
      "shipped": 4,
      "retired": 0
    },
    {
      "label": "D",
      "title": "D — Container operations (what a user came to do)",
      "open": 0,
      "shipped": 3,
      "retired": 0
    },
    {
      "label": "E",
      "title": "E — Images, volumes and networks",
      "open": 0,
      "shipped": 2,
      "retired": 0
    },
    {
      "label": "F",
      "title": "F — Installer and distribution (free, Apache 2.0)",
      "open": 4,
      "shipped": 3,
      "retired": 0
    },
    {
      "label": "G",
      "title": "G — The agent surface (an agent operates this, and pays in tokens)",
      "open": 9,
      "shipped": 2,
      "retired": 0
    },
    {
      "label": "H",
      "title": "H — The public surface (the site a reader and an agent both read)",
      "open": 2,
      "shipped": 12,
      "retired": 0
    }
  ],
  "totals": {
    "open": 25,
    "shipped": 36,
    "retired": 0
  },
  "open": [
    {
      "id": "DD52",
      "status": "💭",
      "block": "A",
      "symptom": "The rival row prints its evidence as one 254-character line, and wrapping it on spaces splits a path",
      "why": "Evidence exists so a user can check it against `where docker`, and a path broken across lines cannot be copied or grepped.",
      "deps": []
    },
    {
      "id": "DD55",
      "status": "📋",
      "block": "A",
      "symptom": "The engine owns a WSL distribution and an app root both named dockerdesk, and a rename orphans them",
      "why": "Those two names are state on a user machine rather than text in a build: renamed with no migration, every image and volume the old distribution holds becomes unreachable.",
      "deps": [
        "DD54"
      ]
    },
    {
      "id": "DD56",
      "status": "📋",
      "block": "A",
      "symptom": "The rival probe carries a rule that exists only because dockerdesk contains docker, and freewilly does not",
      "why": "The rule and its tests go dead the day the distribution is renamed, and a leftover dockerdesk distribution from an older install starts reading as a rival engine.",
      "deps": [
        "DD55"
      ]
    },
    {
      "id": "DD34",
      "status": "📋",
      "block": "C",
      "symptom": "The two windows redeclare their chrome and one red is spelled four times, so a meaning has four definitions",
      "why": "A style that lives in whichever window needed it first drifts silently, and claude-tray declares the colours whose value is not a free choice once, converting at each edge.",
      "deps": []
    },
    {
      "id": "DD35",
      "status": "📋",
      "block": "C",
      "symptom": "Three lists, the engine, the logs and the shell share one window class, so a fourth list grows the same two files",
      "why": "claude-tray's shell owns only the chrome and each destination its own header and footer; here every list repeats the header, empty-state and refresh stanza in full.",
      "deps": [
        "DD34"
      ]
    },
    {
      "id": "DD36",
      "status": "📋",
      "block": "C",
      "symptom": "A row says its state in plain text and carries six always-visible captions, so a list of forty reads as a form",
      "why": "State is the one column scanned down, and the actions are pressed once a session; a tinted chip and a hover-revealed action set are what claude-tray's rows already do.",
      "deps": [
        "DD34"
      ]
    },
    {
      "id": "DD37",
      "status": "📋",
      "block": "C",
      "symptom": "No heading sorts and no list filters, so finding one container among forty is done with the scrollbar",
      "why": "The window is opened with one container in mind; a heading that reorders on click and a box that narrows are what turn a long list into an answer rather than a scroll.",
      "deps": [
        "DD35"
      ]
    },
    {
      "id": "DD38",
      "status": "📋",
      "block": "C",
      "symptom": "No window can be drawn without a running daemon holding the containers the picture is meant to show",
      "why": "claude-tray renders every page from a fixture behind a flag, which is what makes a screenshot reviewable and deterministic, and what gives DD22's capture something to photograph.",
      "deps": []
    },
    {
      "id": "DD39",
      "status": "📋",
      "block": "C",
      "symptom": "The window opens at one fixed size on the primary screen every time and forgets which list was being read",
      "why": "A tool opened several times a day on a two-monitor desk is placed by hand every time, and the tab is the one piece of state the user set on purpose.",
      "deps": []
    },
    {
      "id": "DD61",
      "status": "📋",
      "block": "C",
      "symptom": "A screen copy of the window carries a blurred image of what is behind it, because the Fluent backdrop transmits it",
      "why": "The overlap check cannot answer for this: the intruder is not in front of the window, it is showing through it, so the copy leaks with every assertion satisfied.",
      "deps": []
    },
    {
      "id": "DD32",
      "status": "📋",
      "block": "F",
      "symptom": "An agent meeting this machine has no way to know the surface exists, so it reaches for docker",
      "why": "A capability nobody discovers is one nobody uses, and the allowlist entry that makes the read split pay is a settings file the install never touches.",
      "deps": [
        "DD24 ✅",
        "DD14 ✅"
      ]
    },
    {
      "id": "DD53",
      "status": "📋",
      "block": "F",
      "symptom": "The test guest cannot be returned to a clean snapshot, so the machine a check was measured on is gone once it drifts",
      "why": "A row measured on a bare Windows is unverifiable the moment that guest has WSL, and reverting is the one thing the harness documents and does not do.",
      "deps": []
    },
    {
      "id": "DD54",
      "status": "📋",
      "block": "F",
      "symptom": "Every project, namespace and assembly in the tree spells DockerDesk, so a rename starts at the solution file",
      "why": "A namespace is the spelling every file in the tree repeats, so renaming it after the machine-facing names leaves two products inside one build for as long as that takes.",
      "deps": []
    },
    {
      "id": "DD57",
      "status": "📋",
      "block": "F",
      "symptom": "The installer identifies the product by an AppId with the old name inside it, so a rename installs a second one",
      "why": "Inno Setup identifies a product by AppId alone, so keeping the id upgrades the old entry under a new label and changing it leaves two products installed.",
      "deps": [
        "DD54",
        "DD55"
      ]
    },
    {
      "id": "DD25",
      "status": "📋",
      "block": "G",
      "symptom": "Learning what this machine is running costs five commands, and it repeats in full every session",
      "why": "Discovery is answered by a truncating human-readable table with no cursor, so an agent pays for the whole machine each time and reads four fields out of six hundred lines.",
      "deps": [
        "DD24 ✅"
      ]
    },
    {
      "id": "DD26",
      "status": "📋",
      "block": "G",
      "symptom": "Why a container is not answering is a join across five commands, and inspect is read for four fields",
      "why": "One inspect is three to six hundred lines of JSON paid in full, and the join that turns those fields into a conclusion has no command at all.",
      "deps": [
        "DD24 ✅"
      ]
    },
    {
      "id": "DD27",
      "status": "📋",
      "block": "G",
      "symptom": "A container log is read unbounded, so a restart loop is paid for eight times in identical traces",
      "why": "Logs are the largest token sink here and the read has no cursor, no level, no dedup and no ceiling, so the cost is the size of the file rather than of the answer.",
      "deps": [
        "DD25"
      ]
    },
    {
      "id": "DD28",
      "status": "📋",
      "block": "G",
      "symptom": "Port is already allocated does not say what holds the port, and the answer is not in Docker at all",
      "why": "The daemon knows a bind failed and a Windows process knows which PID owns the socket, so the one refusal an agent cannot act on is the one this app can complete.",
      "deps": [
        "DD24 ✅",
        "DD16 ✅",
        "DD20 ✅"
      ]
    },
    {
      "id": "DD29",
      "status": "📋",
      "block": "G",
      "symptom": "What an agent created is indistinguishable from what the user created, so cleanup is prune or nothing",
      "why": "Prune is scoped to the whole machine and is the one command nobody delegates, so leftovers stay rather than risk a volume the session did not create.",
      "deps": [
        "DD24 ✅"
      ]
    },
    {
      "id": "DD30",
      "status": "📋",
      "block": "G",
      "symptom": "Nothing proves a service is reachable: a running container with a bound port can answer nothing",
      "why": "An agent cannot see, so the gap between the daemon reporting running and the port answering from Windows is closed by you looking, which is the costliest cycle.",
      "deps": [
        "DD26"
      ]
    },
    {
      "id": "DD31",
      "status": "📋",
      "block": "G",
      "symptom": "Every session re-derives the whole machine, because nothing states what moved since the last one",
      "why": "The tray already holds the event stream open, so a delta is a cursor over a running stream and the only mechanism that makes a second session cheaper than the first.",
      "deps": [
        "DD25",
        "DD7 ✅"
      ]
    },
    {
      "id": "DD33",
      "status": "💭",
      "block": "G",
      "symptom": "A client with no shell cannot reach this surface at all, the CLI being the only head there is",
      "why": "A tool schema is re-sent every turn of every session, so a second head is worth its fixed cost only if a shell-less caller exists, which no evidence yet says it does.",
      "deps": [
        "DD24 ✅"
      ]
    },
    {
      "id": "DD58",
      "status": "📋",
      "block": "G",
      "symptom": "The agent surface is invoked as dockerdesk and quoted that way in allowlist patterns matched literally",
      "why": "An allowlist pattern is a string a user pasted into their own settings, so this project cannot migrate it, and DD32 has to write the new name rather than the old one.",
      "deps": [
        "DD54"
      ]
    },
    {
      "id": "DD59",
      "status": "📋",
      "block": "H",
      "symptom": "The site is served from a base path containing the old name, so every published route moves at once",
      "why": "GitHub Pages derives the base path from the repository name, so renaming the repo moves every published URL at once and nothing serves the old ones.",
      "deps": [
        "the GitHub repository rename"
      ]
    },
    {
      "id": "DD60",
      "status": "📋",
      "block": "H",
      "symptom": "Fifteen lines of governed prose name DockerDesk, and the guard denies the edit that would change them",
      "why": "The guard denies the edit, so each one moves through the verb that owns it, and a ledger naming a product nobody can find is where a stale name actively misleads.",
      "deps": []
    }
  ],
  "ledger": [
    {
      "id": "DD1",
      "status": "✅",
      "block": "A",
      "symptom": "A Windows user cannot tell why Docker will not run here: WSL2 missing, virtualization off, or a rival engine",
      "why": "`dockerdesk-preflight` reports the Windows build, virtualization, the WSL2 kernel and any rival engine one row each with the action that fixes it, and exits 1 while a blocking row is not green.",
      "deps": []
    },
    {
      "id": "DD2",
      "status": "✅",
      "block": "A",
      "symptom": "There is no unattended way to put a container engine on Windows without installing Docker Desktop",
      "why": "`dockerdesk-engine --provision` puts upstream Moby 29.7.2 in an owned WSL2 distro and docker.exe where an installer can add it to PATH.",
      "deps": []
    },
    {
      "id": "DD17",
      "status": "✅",
      "block": "A",
      "symptom": "No clean Windows is reachable from here, so a red preflight row and a real install have never been executed",
      "why": "`vm.ps1` runs the product preflight inside a Windows 11 guest through vmrun and reads back what it said.",
      "deps": []
    },
    {
      "id": "DD3",
      "status": "✅",
      "block": "A",
      "symptom": "Nothing starts or stops the engine, and a UI that reports running before the socket answers is lying",
      "why": "`dockerdesk-engine --run` starts the distro and daemon, serves \\.\\pipe\\docker_engine, and reports Running only once the engine answers.",
      "deps": []
    },
    {
      "id": "DD16",
      "status": "✅",
      "block": "A",
      "symptom": "The preflight reports no rival engine on a machine where Docker Desktop is installed per-user and `docker` is on PATH",
      "why": "The row now asks what owns the docker command, resolving it off PATH the way a shell does and reading the registered WSL distributions, and it names every signal it found.",
      "deps": []
    },
    {
      "id": "DD18",
      "status": "✅",
      "block": "A",
      "symptom": "On a Windows 11 that never had WSL, the preflight spends 15 seconds saying it could not read the WSL2 row",
      "why": "The row asks `wsl --status` first, so a bare machine is named in milliseconds with the remedy that applies, and `--version` is only reached once something says WSL is there.",
      "deps": []
    },
    {
      "id": "DD19",
      "status": "✅",
      "block": "A",
      "symptom": "Inside a VM the preflight calls virtualization enabled and clears an install that WSL2 then refuses to start",
      "why": "The row reads whether this machine is itself a guest, and abstains inside one instead of reading HypervisorPresent as proof it can host a hypervisor.",
      "deps": []
    },
    {
      "id": "DD20",
      "status": "✅",
      "block": "A",
      "symptom": "A leftover docker context sends the CLI to another pipe, so docker reports no daemon while this engine is answering",
      "why": "A preflight row reads the active context and names both endpoints, so a CLI pointing elsewhere is visible, and it changes no setting of the user's.",
      "deps": []
    },
    {
      "id": "DD4",
      "status": "✅",
      "block": "B",
      "symptom": "Nothing in this project can ask the engine anything: no client for the Docker API over the Windows named pipe",
      "why": "DockerApi speaks the Engine API over the named pipe with no NuGet dependency: ping, version, containers, and a stream for endpoints that never end.",
      "deps": []
    },
    {
      "id": "DD5",
      "status": "✅",
      "block": "B",
      "symptom": "A container started in a terminal never appears in the window, and the list is only as fresh as the last refresh",
      "why": "EngineEvents reads /events as the daemon writes it and re-opens the stream after every break, so nothing here polls.",
      "deps": []
    },
    {
      "id": "DD6",
      "status": "✅",
      "block": "C",
      "symptom": "Answering is Docker up? costs opening a window, and starting the engine costs a command line",
      "why": "A tray icon carries the engine state as a shape, and its menu starts the engine in a process that outlives the tray or stops it.",
      "deps": []
    },
    {
      "id": "DD7",
      "status": "✅",
      "block": "C",
      "symptom": "There is no window: a user cannot see which containers exist, their state, or the ports they publish",
      "why": "A WPF window lists containers with their ports as links, refreshed by the event stream, and says something designed when it is empty.",
      "deps": []
    },
    {
      "id": "DD21",
      "status": "✅",
      "block": "C",
      "symptom": "The tray icon was not in the visible notification area while the tray was running, so the glance costs a click",
      "why": "The icon registers and Windows files it into the overflow, so the install says where it went and how to keep it in sight, and nothing here promotes itself.",
      "deps": []
    },
    {
      "id": "DD22",
      "status": "✅",
      "block": "C",
      "symptom": "Verifying a window copies the screen, so a capture twice photographed private content that was in front of it",
      "why": "A --capture-window verb renders the window off-screen so nothing else can be in the frame, and the screen copy kept for popups refuses when anything overlaps it.",
      "deps": []
    },
    {
      "id": "DD8",
      "status": "✅",
      "block": "D",
      "symptom": "The list is read-only: a container cannot be started, stopped, restarted or removed from it",
      "why": "Start, stop, restart and remove on every row: the click lands in a pending state, the event stream is what ends it, and a refusal shows the daemon's own sentence where the button is.",
      "deps": []
    },
    {
      "id": "DD9",
      "status": "✅",
      "block": "D",
      "symptom": "A container that exits immediately shows a state and nothing about the cause, so the user leaves for a terminal",
      "why": "A window per container: frame headers stripped, stderr told from stdout, follow on by default, copy-all to the clipboard, and a buffer capped at 5,000 lines that drops from the front.",
      "deps": []
    },
    {
      "id": "DD10",
      "status": "✅",
      "block": "D",
      "symptom": "There is no way into a running container: no shell, so anything the log does not say is unreachable",
      "why": "The terminal the user already has, running docker exec: the image is asked which shell it has first, so one with neither says so on the row instead of opening a window that closes.",
      "deps": []
    },
    {
      "id": "DD11",
      "status": "✅",
      "block": "E",
      "symptom": "Tens of gigabytes of layers accumulate and nothing says which images are dangling or still in use",
      "why": "Images sorted by size, each row saying whether a container holds it or it is dangling, with per-image removal and a dangling-only prune that names the space before the click and after it.",
      "deps": []
    },
    {
      "id": "DD12",
      "status": "✅",
      "block": "E",
      "symptom": "Volumes are invisible: a user cannot see which exist, what they cost on disk, or which containers mount them",
      "why": "Volumes with their sizes and what mounts them, the compose project read off the name, and a deletion that names all of it first because a volume is the one thing here that does not come back.",
      "deps": []
    },
    {
      "id": "DD13",
      "status": "✅",
      "block": "F",
      "symptom": "Nothing states the terms: a visitor cannot tell this is free at any headcount, and no NOTICE covers the bundled engine",
      "why": "Apache-2.0 stated in the README's first paragraph, in LICENSE and in the window's About, with a NOTICE generated from the install manifest so a new download cannot ship unattributed.",
      "deps": []
    },
    {
      "id": "DD14",
      "status": "✅",
      "block": "F",
      "symptom": "There is nothing to hand a user: no executable, no installer, and no uninstall that respects their data",
      "why": "One DockerDesk.exe with every verb behind an argument, an Inno Setup installer that is per-user with no administrator prompt, and an uninstall that asks before deleting the distribution.",
      "deps": []
    },
    {
      "id": "DD15",
      "status": "✅",
      "block": "F",
      "symptom": "Every release is built on one developer's machine, so the first download finds what that machine hid",
      "why": "Two Windows workflows: a check that builds, tests and starts the published .exe on every push, and a tag that drafts a release carrying SHA-256 sums for a person to publish.",
      "deps": []
    },
    {
      "id": "DD23",
      "status": "✅",
      "block": "G",
      "symptom": "Nothing measures what a Docker task costs an agent, so a cheaper surface is an unfalsifiable claim",
      "why": "A benchmark measures the canonical task at 11711 estimated tokens over six calls, and agent-budget.json is the ceiling it reads, so a response that grew fails a build.",
      "deps": []
    },
    {
      "id": "DD24",
      "status": "✅",
      "block": "G",
      "symptom": "Reading a container and deleting a volume are one allowlist decision, so every read costs an approval",
      "why": "read and do are separate argv namespaces so one allowlist line grants every read, and a test drives each read verb and requires every request it made to be a GET.",
      "deps": []
    },
    {
      "id": "DD40",
      "status": "✅",
      "block": "H",
      "symptom": "The site is one hand-written page, dark-only, with every claim typed into the markup that displays it",
      "why": "The landing page renders from a Vite React Tailwind workspace: copy in one content module the sections iterate, and the theme follows the OS.",
      "deps": []
    },
    {
      "id": "DD41",
      "status": "✅",
      "block": "H",
      "symptom": "A static host needs a file per route, and nothing checks that a route has a page or a page a title",
      "why": "Each route prerenders to its own file with a replace-or-throw head, and the route map and metadata table assert against each other in both directions at import time.",
      "deps": []
    },
    {
      "id": "DD42",
      "status": "✅",
      "block": "H",
      "symptom": "A Claude-first product answers an agent only in hydrated markup, in the first thing anybody reads",
      "why": "Every route emits a Markdown twin converted from the same render, a manifest lists the routes and their twin sizes, and llms.txt moves into the build with the twin convention.",
      "deps": []
    },
    {
      "id": "DD43",
      "status": "✅",
      "block": "H",
      "symptom": "The status rows are typed into the page, and five of them are already wrong about what has shipped",
      "why": "The status page and the landing summary are generated from roadkeep export --json on every build, so a shipped task moves its own row and no progress figure is typed.",
      "deps": []
    },
    {
      "id": "DD44",
      "status": "✅",
      "block": "H",
      "symptom": "The hero asserts what the tool is, so what it costs an agent per call is nowhere on the page",
      "why": "The hero autoplays the five-call agent session with its per-call token targets, and the transcript scrolls its own list rather than the window.",
      "deps": []
    },
    {
      "id": "DD45",
      "status": "✅",
      "block": "H",
      "symptom": "Nothing on the site says who the operator is, so the positioning is still a GUI with no licence fee",
      "why": "A section per design law in the order an agent meets them, and the two-actor split, replace the GUI-with-no-licence-fee positioning the pre-DD23 page shipped under.",
      "deps": []
    },
    {
      "id": "DD46",
      "status": "✅",
      "block": "H",
      "symptom": "Nobody configuring an agent can find the read and do split, or the one allowlist line that pays for it",
      "why": "A page for the agent's operator: the read/do split, the one allowlist line Bash(dockerdesk read:*), the DD32 plugin, and the refusals, marked as the designed Block-G surface.",
      "deps": []
    },
    {
      "id": "DD47",
      "status": "✅",
      "block": "H",
      "symptom": "A visitor weighing this against Docker Desktop, Rancher, Podman or a plain WSL2 daemon infers it from prose",
      "why": "A comparison matrix grouped by the law each row comes from, with a column per rival for what it genuinely wins, and a machine-readable table twin.",
      "deps": []
    },
    {
      "id": "DD48",
      "status": "✅",
      "block": "H",
      "symptom": "Everything is one scroll, so a pillar gets a paragraph and there is no page to link at",
      "why": "Five depth pages from one record each, whose route, title and description are read off the same record, so a pillar cannot ship half-declared or untitled.",
      "deps": []
    },
    {
      "id": "DD49",
      "status": "✅",
      "block": "H",
      "symptom": "The og image points at an svg, so every share of this link renders a card with no image at all",
      "why": "A 1200x630 og.png rasterised from public/og.svg on every build, with the mark and the tagline, and og:image points at it on every route.",
      "deps": []
    },
    {
      "id": "DD50",
      "status": "✅",
      "block": "H",
      "symptom": "The site is whatever was last committed to docs, so a broken page is public with no gate between",
      "why": "A workflow_dispatch-only Pages job whose single gate is npm run build (typecheck, the prerender route and head checks), publishing site/dist to the same URL.",
      "deps": []
    },
    {
      "id": "DD51",
      "status": "✅",
      "block": "H",
      "symptom": "A claim on the site that has gone false is invisible until somebody reads the page against the product",
      "why": "node --test asserts the site's own claims: the generated roadmap figures, the route pair and heads, the twin per route with the CTA dropped, the 1200x630 card, and no scrollIntoView.",
      "deps": []
    }
  ],
  "next": "DD25"
};
