<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DockerDesk.Preflight</RootNamespace>
    <AssemblyName>dockerdesk-preflight</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DockerDesk.Core\DockerDesk.Core.csproj" />
  </ItemGroup>

</Project>
