<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DockerDesk.Engine.Cli</RootNamespace>
    <AssemblyName>dockerdesk-engine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DockerDesk.Core\DockerDesk.Core.csproj" />
  </ItemGroup>

</Project>
